# Generated by Django 3.2.4 on 2021-06-22 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cseusername', models.TextField()),
                ('firstname', models.TextField()),
                ('lastname', models.TextField()),
                ('rollnumber', models.TextField()),
                ('section', models.TextField()),
            ],
        ),
    ]
